### ISSUE TITLE
#include "AGeoUtil.h" hides the definition of AGeoUtil::MakePointToPointTube

### ISSUE THREAD

**Issue by akira-okumura** [ROBAST/ROBAST#18]
When ROBAST v2.4.1  is built with ROOT 5.34.36 on El Capitan or Sierra, using #include directive hides a few definitions.

$ root
root [0] .x tutorials/HESS1.C 
=> Works

$ root
root [0] #include "AGeoUtil.h"
root [1] .x tutorials/HESS1.C 
(snip)
Error: MakePointToPointTube() declared but not defined tutorials/HESS1.C:281:
*** Interpreter error recovered ***
=> Error

This does not happen with ROOT 6.08.04.

**Comment by akira-okumura** [comment]
@tomohiroinada Please try the repository HEAD. I added a very temporary workaround in `tutorials/HESS1.C` but it should work with ROOT 5. If it works I will release v2.4.2.

**Comment by tomohiroinada** [comment]
In my case, it didn't work...

$ ls
LICENSE                 README.md               libROBAST.dylib         mkhtml.sh
Makefile                SCHOTT_catalog_2011.txt libROBAST.rootmap       src
README                  include                 misc                    tutorials

$ root -l
root [0] .include /Users/cta_icrr/ROBAST/ROBAST-2.4.1/include
root [1] .x tutorials/HESS1.C 
Error in <TMacOSXSystem::DynamicPathName>: libROBAST.so does not exist in /usr/local/cmake_root/lib:/usr/local/cmake_root/lib:/usr/local/cmake_root/lib::/Users/cta_icrr/ROBAST/ROBAST-2.4.1:::.:/usr/local/cmake_root/lib::/usr/local/cmake_root/cint/cint/stl
Error in <TCint::AutoLoadCallback>: failure loading library libROBAST.so for class AOpticsManager
Error in <TMacOSXSystem::DynamicPathName>: libROBAST.so does not exist in /usr/local/cmake_root/lib:/usr/local/cmake_root/lib:/usr/local/cmake_root/lib::/Users/cta_icrr/ROBAST/ROBAST-2.4.1:::.:/usr/local/cmake_root/lib::/usr/local/cmake_root/cint/cint/stl
Error in <TCint::AutoLoadCallback>: failure loading library libROBAST.so for class AOpticsManager
Error: Function cm() is not defined in current scope  tutorials/HESS1.C:7:
*** Interpreter error recovered ***

root [2] #include "AGeoUtil.h"
root [3] .x tutorials/HESS1.C 
Error in <TMacOSXSystem::DynamicPathName>: libROBAST.so does not exist in /usr/local/cmake_root/lib:/usr/local/cmake_root/lib:/usr/local/cmake_root/lib::/Users/cta_icrr/ROBAST/ROBAST-2.4.1:::.:/usr/local/cmake_root/lib::/usr/local/cmake_root/cint/cint/stl
Error in <TCint::AutoLoadCallback>: failure loading library libROBAST.so for class AOpticsManager
Error in <TMacOSXSystem::DynamicPathName>: libROBAST.so does not exist in /usr/local/cmake_root/lib:/usr/local/cmake_root/lib:/usr/local/cmake_root/lib::/Users/cta_icrr/ROBAST/ROBAST-2.4.1:::.:/usr/local/cmake_root/lib::/usr/local/cmake_root/cint/cint/stl
Error in <TCint::AutoLoadCallback>: failure loading library libROBAST.so for class AOpticsManager
Error: Function cm() is not defined in current scope  tutorials/HESS1.C:7:
*** Interpreter error recovered ***

**Comment by akira-okumura** [comment]
ROBAST 2.4.1 is an old release which is different from the HEAD.
```
$ git clone https://github.com/ROBAST/ROBAST.git ROBAST
```

**Comment by tomohiroinada** [comment]
Thank you so much!!!
It worked.

$ git clone https://github.com/ROBAST/ROBAST.git ROBAST
$ make
$ LICENSE                 README.md               libROBAST.rootmap       mkhtml.sh
Makefile                SCHOTT_catalog_2011.txt libROBAST.so            src
README                  include                 misc                    tutorials
$ root -l
root [0] .include /Users/cta_icrr/ROBAST/ROBAST/include
root [1] .x tutorials/HESS1.C

It works !!

$ root -l
root [0] .include /Users/cta_icrr/ROBAST/ROBAST/include
root [1] #include "AGeoUtil.h"
root [2] .x tutorials/HESS1.C 
Info in <TGeoManager::TGeoManager>: Geometry manager, HESS CT3 System created
Info in <AOpticsManager::SetTopVolume>: Top volume is world. Master volume is world
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
Error: MakePointToPointTube() declared but not defined tutorials/HESS1.C:298:
*** Interpreter error recovered ***

**Comment by akira-okumura** [comment]
I added just `#ifndef` statement in `tutorials/HESS1.C` to avoid include the problematic header file `AGeoUtil.h`. That's why `#include "AGeoUtil.h"` prevents you from using `AGeoUtil::MakePointToPointTube`. I do not know how to fix it at the moment, but at leas `HESS1.C` works.

**Comment by akira-okumura** [comment]
FYI.

I am looking for a better solution for this issue by consulting ROOT experts at this RootTalk thread.
https://groups.cern.ch/group/roottalk/Lists/Archive/Flat.aspx?RootFolder=%2Fgroup%2Froottalk%2FLists%2FArchive%2FMakefile%20for%20a%20user%20library%20on%20El%20Capitan%20and%20Sierra&FolderCTID=0x01200200A201AF59FD011C4E9284C43BF0CDA2A4

**Comment by tomohiroinada** [comment]
Thank you very much for your information.

I also tried to run HexOkumuraCone.C after I added #ifdef as you did.
HexOkumuraCone.C could run.
So I will try to run others adding #ifdef.

anyway, Thank you so much for your support.

**Comment by akira-okumura** [comment]
What error doe you get in `HexOkumuraCone.C`? I don't get any with ROOT 5 on El Capitan or Sierra.

**Comment by tomohiroinada** [comment]
Sorry for confusing.
I didn't check HexOkumuraCone.C  run whether or not before I added #ifdef.
Just I would like to know others source could run after adding #ifdef.

**Comment by akira-okumura** [comment]
Could you try the latest version? This problem should have been fixed.

**Comment by tomohiroinada** [comment]
I tried and it works with ROOT5.
Thank you so much.

Tomo

**Comment by akira-okumura** [comment]
v2.4.2 has been released.

**Comment by tomohiroinada** [comment]
I 'm sorry.
I can't find v2.4.2 in https://robast.github.io/download.html.
Where should I see ?

Tomo

**Comment by akira-okumura** [comment]
The download page is not automatically updated as you can imagine.

Please go to https://github.com/ROBAST/ROBAST/releases or try
```
$ git clone -b v2.4.2 https://github.com/ROBAST/ROBAST.git ROBAST
```
or
```
$ git clone https://github.com/ROBAST/ROBAST.git ROBAST
$ cd ROBAST
$ git checkout v2.4.2
```

**Comment by tomohiroinada** [comment]
Thank you.
I could download v2.4.2.
It works.

Thank you so much again.

Tomo
