### ISSUE TITLE
Problem running ROBAST HESS example on Ubuntu machine with Root version 6.08

### ISSUE THREAD

**Issue by astrame** [ROBAST/ROBAST#20]
Hi,

I am using pre compiled binary for root from https://root.cern.ch/content/release-60902 (Ubuntu 16) and the latest stable version of ROBAST 2.4.2. While executing the steps mentioned on https://robast.github.io/user_guide.html, I get an error when trying to run the HESS example in tutorial. The error is below:

root [0] .x HESS1.C+
cling::DynamicLibraryManager::loadLibrary(): /home/neha/Astrome_Code/ROBAST/libROBAST.so: undefined symbol: _ZTI9TGeoTrack

**Comment by astrame** [comment]
The solution for this error is to modify the Makefile in ROBAST to include a line 
`EXPLLINKLIBS  = $(ROOTLIBS) $(ROOTGLIBS)` 

right before these three statements:

```
ifneq ($(EXPLLINKLIBS), )
EXPLLINKLIBS	+= -lGeom -lGeomPainter
endif
```

After this, I ran

```
make clean
make 

```
commands in the ROBAST folder.

**Comment by akira-okumura** [comment]
Thank you for trying ROBAST.

It appears that your issue is very similar to issue #16. Would you please try
<pre>
   root [0] gSystem->Load("libGeomPainter")
</pre>

**Comment by akira-okumura** [comment]
Ah, ok. You found the solution. Yes, it is a dependency issue in the linker. My Makefile was working fine a while ago, and it is very strange that ROBAST has a dependency on libGeomPainter. But at some point before, ROOT changed something internally.

I will fix Makefile once I sit in front of my Linux machine.

**Comment by astrame** [comment]
Yes, the issue is similar to issue #16 but the solution there does not work for the problem. Thanks, Akira. I am grateful that you have shared the ROBAST code.

**Comment by akira-okumura** [comment]
Fixed. Thank you for your report. Now v2.4.3 is available.
https://github.com/ROBAST/ROBAST/releases/tag/v2.4.3
