### ISSUE TITLE
ROOT 5.34.14 make error

### ISSUE THREAD

**Issue by anatolii-zenin** [ROBAST/ROBAST#27]
/usr/local/GNU/4.7.3/bin/g++ -O2 -Wall -fPIC -pthread -m64 -I/usr/local/gcc473/root_v5.34.14/include/root  -Wall -g -Iinclude -c src/ALens.cxx -o src/ALens.o
src/ALens.cxx: In constructor 'ALens::ALens(const char*, const TGeoShape*, const TGeoMedium*)':
src/ALens.cxx:33:21: error: 'DummyMedium' is not a member of 'TGeoVolume'
make: *** [src/ALens.o] Error 1

**Comment by akira-okumura** [comment]
It compiles now, and so you can use it with 5.34/14. But please note that the unit test script fails on the ICRR server. I will fix it later.
