### ISSUE TITLE
ARay propagating outside a light cone hit focal plane

### ISSUE THREAD

**Issue by cperennes** [ROBAST/ROBAST#31]
**Describe the bug**
Some ARay are focused (kFocus = true) whereas they did not get into the light cone and should not be able to hit the focal surface.

**To Reproduce**
1. Using HexOkumuraCone.C
2. Fix theta = 33.5°, close the opening angle and phi = 0°
3. Draw some focused ARay

**Screenshots**
[Okumura_cone_33.5.pdf](https://github.com/ROBAST/ROBAST/files/2691049/Okumura_cone_33.5.pdf)

**Environment (please complete the following information):**
 - OS: macOS 10.14.2
 - ROOT: 6.14.02
 - ROBAST: v2.5.0

**Minimum script to reproduce the issue**
[Okumura_simple.txt](https://github.com/ROBAST/ROBAST/files/2691134/Okumura_simple.txt)

**Comment by akira-okumura** [comment]
It looks that your cone exit aperture is a little bit smaller than the focal surface.
<img width="834" alt="screen shot 2018-12-19 at 7 14 23" src="https://user-images.githubusercontent.com/2981330/50186288-bed54300-035d-11e9-91f2-7250b67b607c.png">
